# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReceiptManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReceiptManager
pod 'RxSwift', "6.2.0"
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'RxDataSources'
pod 'Action'
pod 'RxCoreData'
pod 'SwiftLint'
pod 'Mantis', '~> 2.14.1'


end
