# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end

target 'ReceiptManager' do
    pod 'RxSwift', "6.2.0"
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'RxCoreData'
    pod 'SwiftLint'
    pod 'Mantis', '~> 2.14.1'
    pod 'ReactorKit'
    pod 'RxGesture'
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    use_frameworks! :linkage => :static

    target 'ReceiptManagerTests' do
        inherit! :search_paths
	pod 'RxTest'
    end
end
